"""add pass field

Revision ID: 5acbac5028dd
Revises: aca8e8fe419e
Create Date: 2024-06-25 19:56:28.401681

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5acbac5028dd'
down_revision: Union[str, None] = 'aca8e8fe419e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sqlmodel.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
